import "./styles.css";
import { ApiError, api } from "./api";
import { currentUser, isAuthenticated, role, signIn, signOut } from "./auth";
import { canAccess, go, guard, route, visiblePages } from "./router";
import type { Availability, Facility, Prediction, Vehicle } from "./types";

const app = document.querySelector<HTMLDivElement>("#app")!;
const esc = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char] || char));
const fmtDate = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "Not available";
const fmtMoney = (value: unknown) => typeof value === "number" && value > 0 ? `₹${value.toFixed(0)}/hr` : "Not available";
const errorText = (error: unknown) => error instanceof ApiError ? error.message : "Something went wrong. Please try again.";

function layout(content: string, active: string) {
  const user = currentUser();
  const pages: Record<string, [string, string]> = { overview: ["Overview", "◈"], recommendations: ["Recommendations", "✦"], "live-map": ["Live map", "⌖"], entry: ["Parking entry", "↗"], exit: ["Parking exit", "↘"], "find-vehicle": ["Find my vehicle", "⌖"], vehicles: ["My vehicles", "▱"], places: ["Places", "▦"], layout: ["Slot layout", "▦"], reports: ["Reports", "▤"], predictions: ["Predictions", "◉"], feedback: ["Feedback", "✎"], operations: ["Gate scanners", "⌁"], "scanner-console": ["Scanner console", "▣"], admin: ["Admin console", "⚙"] };
  const nav = visiblePages().map((page) => { const [label, icon] = pages[page] || [page, "•"]; return `<button class="nav-item ${active === page ? "active" : ""}" data-route="${page}"><span>${icon}</span>${label}</button>`; }).join("");
  return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">◉</div><div><strong>PARKWISE</strong><small>PREDICTIVE PARKING INTELLIGENCE</small></div></div><div class="nav-group"><span class="nav-caption">Workspace</span>${nav}</div><div class="sidebar-bottom"><span class="status-dot"></span> API connected<div class="user-chip"><b>${esc(user?.full_name)}</b><small>${esc(user?.role)}</small></div><button class="ghost-button" id="logout">Log out</button></div></aside><main class="main"><header class="topbar"><div><span class="eyebrow">PARKING INTELLIGENCE / LIVE NETWORK</span><span class="mobile-title">PARKWISE</span></div><div class="topbar-actions"><span class="status-pill">● SYSTEM NOMINAL</span><span class="last-updated">${new Date().toLocaleTimeString()}</span></div></header><section class="content">${content}</section></main></div>`;
}

function cardMetric(label: string, value: string, help: string, accent = "cyan") { return `<article class="metric-card accent-${accent}"><span class="metric-label">${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(help)}</small></article>`; }
function status(value: string) { return `<span class="badge badge-${value.toLowerCase()}">${esc(value)}</span>`; }
function showError(message: string) { return `<div class="state error-state"><b>Unable to load this section</b><span>${esc(message)}</span><button class="secondary-button" data-refresh>Retry</button></div>`; }
function showEmpty(message: string) { return `<div class="state"><b>${esc(message)}</b><span>No records were returned by the API.</span></div>`; }

async function customerOverview() {
  try {
    const [availability, facilities] = await Promise.all([api.availability(), api.facilities()]);
    const total = availability.reduce((sum, item) => sum + item.total_capacity, 0);
    const occupied = availability.reduce((sum, item) => sum + item.occupied_spaces, 0);
    const available = availability.reduce((sum, item) => sum + item.available_spaces, 0);
    const cards = availability.map((item) => { const state = item.available_spaces === 0 ? "FULL" : item.occupancy_percentage >= 75 ? "LIMITED" : "AVAILABLE"; return `<article class="place-card"><div class="card-top"><div><h3>${esc(item.facility_name)}</h3><p>${esc(facilities.find((f) => f.id === item.facility_id)?.address || "Address unavailable")}</p></div>${status(state)}</div><div class="place-number"><strong>${item.available_spaces}</strong><span>/ ${item.total_capacity} available</span></div><div class="bar"><i style="width:${Math.min(100, item.occupancy_percentage)}%"></i></div><div class="card-meta"><span>${item.occupancy_percentage.toFixed(1)}% occupied</span><span>Updated ${fmtDate(item.last_update_time)}</span></div><div class="card-actions"><button class="secondary-button" data-route="live-map">View location</button><button class="secondary-button" data-route="entry">Find parking</button></div></article>`; }).join("");
    return `<div class="hero"><div><span class="eyebrow">PARKING INTELLIGENCE / LIVE NETWORK</span><h1>Find your next spot <em>before you arrive.</em></h1><p>PARKWISE combines occupancy, facility data, and availability prediction to help every arrival start with a confident decision.</p></div><div class="demo-notice"><b>DEMO DATA ACTIVE</b><span>Prediction results use simulated training data and are estimates.</span></div></div><div class="metrics">${cardMetric("Monitored parking places", String(availability.length), "Active facilities", "cyan")}${cardMetric("Current occupancy", `${total ? (occupied / total * 100).toFixed(1) : "—"}%`, `${occupied} occupied spaces`, "blue")}${cardMetric("Available slots", String(available), "Calculated from active sessions", "green")}${cardMetric("System health", "Connected", "FastAPI operational", "purple")}</div><div class="section-heading"><div><span class="eyebrow">LIVE AVAILABILITY</span><h2>Parking-place network</h2></div><button class="secondary-button" data-route="live-map">Open live map →</button></div><div class="place-grid">${cards || showEmpty("No active parking places")}</div><div class="two-column"><section class="panel"><div class="section-heading compact"><h2>Occupancy overview</h2><span class="muted">Current sessions</span></div><div class="chart-bars">${availability.map((item) => `<div class="bar-row"><span title="${esc(item.facility_name)}">${esc(item.facility_name)}</span><div class="bar"><i style="width:${Math.min(100, item.occupancy_percentage)}%"></i></div><b>${item.occupancy_percentage.toFixed(0)}%</b></div>`).join("")}</div></section><section class="panel"><div class="section-heading compact"><h2>Quick actions</h2></div><div class="quick-actions"><button data-route="entry"><b>Start parking entry</b><span>Select a vehicle and facility</span></button><button data-route="exit"><b>Exit parking</b><span>Use your signed ticket QR</span></button><button data-route="find-vehicle"><b>Find my vehicle</b><span>View your active slot</span></button><button data-route="feedback"><b>Report ground truth</b><span>Help improve availability</span></button></div></section></div>`;
  } catch (error) { return showError(errorText(error)); }
}

async function adminOverview() {
  try {
    const [facilities, availability, events, users] = await Promise.all([api.facilities(), api.availability(), api.scanEvents(20), api.users()]);
    const totalCapacity = availability.reduce((sum, item) => sum + item.total_capacity, 0);
    const occupied = availability.reduce((sum, item) => sum + item.occupied_spaces, 0);
    return `<div class="hero"><div><span class="eyebrow">ADMIN OPERATIONS / CONTROL CENTER</span><h1>Run every parking place from one dashboard.</h1><p>Create locations, configure capacity, register gates and scanners, and monitor live occupancy from the administrative workspace.</p></div><div class="demo-notice"><b>ADMIN ACCESS</b><span>Changes are protected by FastAPI role enforcement.</span></div></div><div class="metrics">${cardMetric("Parking places", String(facilities.length), "Configured facilities", "cyan")}${cardMetric("Occupancy", `${totalCapacity ? (occupied / totalCapacity * 100).toFixed(1) : "0"}%`, `${occupied} occupied spaces`, "blue")}${cardMetric("Scan events", String(events.length), "Recent gate activity", "green")}${cardMetric("Users", String(users.length), "Registered accounts", "purple")}</div><div class="section-heading"><div><span class="eyebrow">ADMIN WORKSPACE</span><h2>What do you want to manage?</h2></div></div><div class="quick-actions"><button data-route="places"><b>Add a parking place</b><span>Location, capacity, address, and pricing</span></button><button data-route="layout"><b>Configure zones and slots</b><span>Build the physical parking layout</span></button><button data-route="operations"><b>Register gates and scanners</b><span>Set up entry and exit devices</span></button><button data-route="reports"><b>Open reports</b><span>Sessions, scan history, and exports</span></button></div><section class="panel"><div class="section-heading compact"><h2>Live facility status</h2><span class="muted">${facilities.length} configured places</span></div>${availability.length ? `<div class="place-grid">${availability.map((item) => `<article class="place-card"><div class="card-top"><div><h3>${esc(item.facility_name)}</h3><p>${item.available_spaces} of ${item.total_capacity} spaces available</p></div>${status(item.available_spaces === 0 ? "FULL" : "AVAILABLE")}</div><div class="bar"><i style="width:${Math.min(100, item.occupancy_percentage)}%"></i></div><div class="card-meta"><span>${item.occupancy_percentage.toFixed(1)}% occupied</span><span>Updated ${fmtDate(item.last_update_time)}</span></div></article>`).join("")}</div>` : showEmpty("No parking places configured")}</section>`;
  } catch (error) { return showError(errorText(error)); }
}

async function liveMap() {
  try { const [availability, facilities] = await Promise.all([api.availability(), api.facilities()]); const withCoords = facilities.filter((item) => item.latitude !== null && item.longitude !== null); const list = availability.map((item) => `<article class="list-row"><div><b>${esc(item.facility_name)}</b><span>${item.available_spaces} available · ${item.occupancy_percentage.toFixed(1)}% occupied</span></div>${status(item.available_spaces === 0 ? "FULL" : item.occupancy_percentage >= 75 ? "LIMITED" : "AVAILABLE")}</article>`).join(""); return `<div class="page-title"><span class="eyebrow">GEOSPATIAL INTELLIGENCE</span><h1>Live parking network</h1><p>Map coordinates and occupancy are read from the authenticated API.</p></div><div class="map-layout"><section class="map-panel"><div class="map-grid"><span>MAP PREVIEW</span>${withCoords.map((place, index) => `<button class="map-pin pin-${index % 4}" title="${esc(place.name)}" style="left:${20 + index * 17}%;top:${28 + (index % 3) * 20}%">${index + 1}</button>`).join("")}</div><p class="muted">${withCoords.length ? `${withCoords.length} places have coordinates. Connect a map provider for full pan and zoom.` : "Map coordinates are unavailable from the API."}</p></section><section class="panel"><div class="section-heading compact"><h2>Network pulse</h2><span class="status-pill">${availability.length} places</span></div>${list || showEmpty("No availability records")}</section></div>`; } catch (error) { return showError(errorText(error)); }
}

async function entryPage() {
  try { const [vehicles, facilities, availability] = await Promise.all([api.vehicles(), api.facilities(), api.availability()]); return `<div class="page-title"><span class="eyebrow">PARKING OPERATIONS</span><h1>Start a parking session</h1><p>Choose a registered vehicle and let the API assign a compatible available slot.</p></div><div class="form-panel"><form id="entry-form"><label>Vehicle<select name="vehicle_id" required>${vehicles.map((v) => `<option value="${v.id}">${esc(v.registration_number)} · ${v.vehicle_type}</option>`).join("")}</select></label><label>Parking place<select name="facility_id" required>${facilities.filter((f) => f.is_active).map((f) => `<option value="${f.id}">${esc(f.name)} · ${availability.find((a) => a.facility_id === f.id)?.available_spaces ?? "—"} available</option>`).join("")}</select></label><label>Entry method<select name="entry_method"><option value="SELF_SERVICE">Self service</option><option value="QR">Scanner / slot QR</option><option value="MANUAL" ${role() === "ADMIN" || role() === "ATTENDANT" ? "" : "disabled"}>Manual operator entry</option></select></label><label>Slot QR token <span class="muted">required for scanner entry</span><input name="slot_qr_token" placeholder="Paste decoded slot QR token" /></label><button class="primary-button" type="submit">Generate digital ticket →</button><div id="form-message"></div></form></div>`; } catch (error) { return showError(errorText(error)); }
}

async function exitPage() { return `<div class="page-title"><span class="eyebrow">PARKING OPERATIONS</span><h1>Exit parking</h1><p>Validate the signed ticket token and release the assigned slot in one transaction.</p></div><div class="form-panel"><form id="exit-form"><label>Ticket ID<input name="ticket_id" placeholder="PW-…" required /></label><label>Signed ticket QR token<textarea name="qr_token" placeholder="Paste the decoded ticket QR token" required></textarea></label><button class="primary-button" type="submit">Confirm QR exit →</button><div id="form-message"></div></form></div>`; }

async function findVehicle() { try { const ticket = await api.activeTicket(); return `<div class="page-title"><span class="eyebrow">VEHICLE LOCATION</span><h1>Find my vehicle</h1><p>Your current parking location, limited to your authenticated account.</p></div><section class="ticket"><div class="ticket-head"><span class="eyebrow">ACTIVE DIGITAL TICKET</span>${status(ticket.status)}</div><h2>${esc(ticket.facility_name)}</h2><div class="ticket-grid"><span>Ticket <b>${esc(ticket.ticket_id)}</b></span><span>Vehicle <b>${esc(ticket.registration_number)}</b></span><span>Zone <b>${esc(ticket.zone_name)}</b></span><span>Row <b>${esc(ticket.row_label)}</b></span><span>Slot <b>${esc(ticket.slot_code)}</b></span><span>Entry <b>${fmtDate(ticket.entry_time)}</b></span></div><img class="qr" src="data:image/png;base64,${ticket.qr_png_base64}" alt="Signed ticket QR" /></section>`; } catch (error) { return error instanceof ApiError && error.status === 404 ? showEmpty("No active parked vehicle found") : showError(errorText(error)); } }

async function places() { try { const facilities = await api.facilities(); return `<div class="page-title"><span class="eyebrow">ADMINISTRATION</span><h1>Parking places and locations</h1><p>Add each college parking location with its address, map coordinates, capacity, and operating rate.</p></div><div class="form-panel"><h2>Add a parking place</h2><form id="facility-form"><div class="two-column"><label>Place name<input name="name" required placeholder="North Campus Parking" /></label><label>Address<input name="address" required placeholder="Main campus, Gate 1" /></label><label>Total capacity<input name="total_capacity" type="number" min="1" required placeholder="100" /></label><label>Price per hour <span class="muted">optional</span><input name="price_per_hour" type="number" min="0" step="0.01" placeholder="0" /></label><label>Latitude <span class="muted">optional</span><input name="latitude" type="number" min="-90" max="90" step="any" placeholder="18.5204" /></label><label>Longitude <span class="muted">optional</span><input name="longitude" type="number" min="-180" max="180" step="any" placeholder="73.8567" /></label></div><button class="primary-button" type="submit">Create parking place →</button><div id="facility-message"></div></form></div><section class="place-grid">${facilities.map((f) => `<article class="place-card"><div class="card-top"><div><h3>${esc(f.name)}</h3><p>${esc(f.address)}</p></div>${status(f.is_active ? "AVAILABLE" : "OFFLINE")}</div><div class="ticket-grid"><span>Capacity <b>${f.total_capacity}</b></span><span>Coordinates <b>${f.latitude == null ? "Not set" : `${f.latitude}, ${f.longitude}`}</b></span><span>Rate <b>${fmtMoney(f.price_per_hour)}</b></span></div><button class="secondary-button" data-route="layout">View slot layout</button></article>`).join("") || showEmpty("No parking places")}</section>`; } catch (error) { return showError(errorText(error)); } }

async function vehiclesPage() { try { const vehicles = await api.vehicles(); return `<div class="page-title"><span class="eyebrow">CUSTOMER PROFILE</span><h1>My vehicles</h1><p>Register the vehicles you are allowed to park. A vehicle registration is used by the gate scanner during entry.</p></div><div class="form-panel"><h2>Register a vehicle</h2><form id="vehicle-form"><label>Registration number<input name="registration_number" required placeholder="MH12AB1234" /></label><label>Vehicle type<select name="vehicle_type"><option value="CAR">Car</option><option value="MOTORCYCLE">Motorcycle</option><option value="BICYCLE">Bicycle</option><option value="VAN">Van</option><option value="EV">Electric vehicle</option><option value="ACCESSIBLE">Accessible vehicle</option></select></label><button class="primary-button" type="submit">Add vehicle →</button><div id="vehicle-message"></div></form></div><section class="panel"><h2>Registered vehicles</h2>${vehicles.length ? `<div class="table-wrap"><table><thead><tr><th>Registration</th><th>Type</th><th>Status</th></tr></thead><tbody>${vehicles.map((v) => `<tr><td>${esc(v.registration_number)}</td><td>${esc(v.vehicle_type)}</td><td>Ready for parking</td></tr>`).join("")}</tbody></table></div>` : showEmpty("No vehicles registered")}</section>`; } catch (error) { return showError(errorText(error)); } }

async function layoutPage() { try { const facilities = await api.facilities(); if (!facilities.length) return showEmpty("Create a parking place first"); const facility = facilities[0]; const zones = await api.zones(facility.id); const zone = zones[0]; const slots = zone ? await api.slots(zone.id) : []; return `<div class="page-title"><span class="eyebrow">SLOT OPERATIONS</span><h1>${esc(facility.name)} layout</h1><p>Availability states are returned by the slot API.</p></div>${zones.map((z) => `<section class="panel"><div class="section-heading compact"><h2>${esc(z.name)}</h2><span class="muted">${z.vehicle_type} · capacity ${z.capacity}</span></div>${z.id === zone?.id ? `<div class="slot-grid">${slots.map((s) => `<div class="slot slot-${s.status.toLowerCase()}"><b>${esc(s.slot_code)}</b><span>${esc(s.status)}</span><small>${esc(s.row_label)}</small></div>`).join("") || showEmpty("No slots configured")}</div>` : `<p class="muted">Select this zone from the admin layout controls to load its slots.</p>`}</section>`).join("") || showEmpty("No zones configured")}`; } catch (error) { return showError(errorText(error)); } }

async function reports() { try { const [daily, peaks, sessions, scannerSummary] = await Promise.all([api.dailyReport(30), api.peakReport(90), api.sessionsReport(90), api.scannerSummary(30)]); return `<div class="page-title"><span class="eyebrow">ANALYTICS</span><h1>Reports and exports</h1><p>Operational reports include parking sessions and physical scanner activity.</p></div><div class="metrics">${cardMetric("Total entries", String(sessions.length), "Last 90 days", "cyan")}${cardMetric("Completed sessions", String(sessions.filter((s: any) => s.status === "COMPLETED").length), "Recorded exits", "green")}${cardMetric("Scanner days", String(scannerSummary.length), "Last 30 days", "purple")}</div><div class="two-column"><section class="panel"><h2>Daily activity</h2><pre class="data-preview">${esc(JSON.stringify(daily, null, 2))}</pre></section><section class="panel"><h2>Download</h2><p class="muted">Exports contain sessions and scanner events for the selected reporting window.</p><button class="primary-button" id="download-csv">Download CSV report</button><button class="secondary-button" id="download-xlsx">Download Excel workbook</button></section></div><section class="panel"><h2>Scanner activity</h2><pre class="data-preview">${esc(JSON.stringify(scannerSummary, null, 2))}</pre></section>`; } catch (error) { return showError(errorText(error)); } }

async function predictions() { try { const [metrics, predictions] = await Promise.all([api.metrics(), api.predictions()]); return `<div class="page-title"><span class="eyebrow">MODEL INTELLIGENCE</span><h1>30-minute predictions</h1><p>Predictions are estimates from simulated historical data and are not real-time guarantees.</p></div><div class="metrics">${cardMetric("Model MAE", metrics.model_mae == null ? "Not available" : `${metrics.model_mae}`, "Spaces", "cyan")}${cardMetric("RMSE", metrics.model_rmse == null ? "Not available" : `${metrics.model_rmse}`, "Spaces", "blue")}${cardMetric("R²", metrics.model_r2 == null ? "Not available" : `${metrics.model_r2}`, "Model fit", "purple")}${cardMetric("Model version", metrics.dataset_type || "Not available", "Data source", "yellow")}</div><section class="panel"><div class="section-heading compact"><h2>Latest facility predictions</h2><span class="status-pill">+${metrics.prediction_horizon_minutes} min</span></div>${predictions.length ? `<div class="table-wrap"><table><thead><tr><th>Facility</th><th>Predicted available</th><th>Target time</th><th>Model</th></tr></thead><tbody>${predictions.map((p) => `<tr><td>${esc(p.facility_id)}</td><td>${p.predicted_available_spaces}</td><td>${fmtDate(p.target_time)}</td><td>${esc(p.model_version)}</td></tr>`).join("")}</tbody></table></div>` : showEmpty("No predictions have been stored")}</section></section>`; } catch (error) { return showError(errorText(error)); } }

function feedback() { return `<div class="page-title"><span class="eyebrow">GROUND TRUTH</span><h1>Send feedback</h1><p>Help the team identify availability, QR, slot, and maintenance issues.</p></div><div class="form-panel"><form id="feedback-form"><label>Category<select name="category"><option>AVAILABILITY</option><option>SAFETY</option><option>CLEANLINESS</option><option>ACCESSIBILITY</option><option>OTHER</option></select></label><label>Session ID <span class="muted">optional</span><input name="session_id" type="number" /></label><label>Observed available spaces <span class="muted">optional</span><input name="reported_available_spaces" type="number" min="0" /></label><label>Description<textarea name="description" minlength="5" required placeholder="What did you observe?"></textarea></label><button class="primary-button" type="submit">Submit feedback →</button><div id="form-message"></div></form></div>`; }

async function admin() { try { const [users, audits] = await Promise.all([api.users(), api.audits()]); return `<div class="page-title"><span class="eyebrow">ADMIN CONSOLE</span><h1>System operations</h1><p>Administrative views are protected by backend role enforcement.</p></div><div class="metrics">${cardMetric("Users", String(users.length), "Registered accounts", "cyan")}${cardMetric("Audit events", String(audits.length), "Latest records", "purple")}</div><div class="two-column"><section class="panel"><h2>Users</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>${users.map((u) => `<tr><td>${esc(u.full_name)}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${u.is_active ? "Active" : "Inactive"}</td></tr>`).join("")}</tbody></table></div></section><section class="panel"><h2>Audit records</h2><pre class="data-preview">${esc(JSON.stringify(audits.slice(0, 12), null, 2))}</pre></section></div>`; } catch (error) { return showError(errorText(error)); } }

async function operations() {
  try {
    const [facilities, events] = await Promise.all([api.facilities(), api.scanEvents(50)]);
    const sections = await Promise.all(facilities.map(async (facility) => {
      const gates = await api.gates(facility.id);
      const gateSections = await Promise.all(gates.map(async (gate) => {
        const scanners = await api.scanners(gate.id);
        return `<article class="list-row"><div><b>${esc(gate.name)}</b><span>${gate.gate_type} · ${gate.is_active ? "Active" : "Inactive"}</span><small>${scanners.length ? scanners.map((s) => `${esc(s.name)} (${esc(s.device_identifier)}) · ${s.is_active ? "ready" : "revoked"} · last seen ${fmtDate(s.last_seen_at)}`).join(" · ") : "No scanner registered"}</small></div><div>${scanners.map((s) => s.is_active ? `<button class="secondary-button compact-button" data-revoke-scanner="${s.id}">Revoke</button><button class="secondary-button compact-button" data-regenerate-scanner="${s.id}">Regenerate</button>` : `<button class="secondary-button compact-button" data-regenerate-scanner="${s.id}">Regenerate key</button>`).join("")}</div></article>`;
      }));
      return `<section class="panel"><div class="section-heading compact"><div><h2>${esc(facility.name)}</h2><span class="muted">${gates.length} configured gates</span></div></div>${gateSections.join("") || showEmpty("No gates configured")}</section>`;
    }));
    return `<div class="page-title"><span class="eyebrow">PHYSICAL OPERATIONS</span><h1>Gate and scanner registry</h1><p>Configure each college entry/exit point once, then attach the scanner device that will produce the audit trail.</p></div><div class="metrics">${cardMetric("Places", String(facilities.length), "API facilities", "cyan")}${cardMetric("Scan events", String(events.length), "Latest records", "purple")}${cardMetric("Successful", String(events.filter((e) => e.result === "SUCCESS").length), "Recent scans", "green")}</div><div class="two-column"><section class="form-panel"><h2>Register a gate</h2><form id="gate-form"><label>Parking place<select name="facility_id" required>${facilities.map((f) => `<option value="${f.id}">${esc(f.name)}</option>`).join("")}</select></label><label>Gate name<input name="name" required placeholder="Main entrance" /></label><label>Direction<select name="gate_type"><option value="BOTH">Entry and exit</option><option value="ENTRY">Entry only</option><option value="EXIT">Exit only</option></select></label><button class="primary-button" type="submit">Create gate →</button><div id="gate-message"></div></form></section><section class="form-panel"><h2>Register a scanner</h2><p class="muted">Save this one-time scanner key securely. It will never appear in the scanner list.</p><form id="scanner-form"><label>Gate<select name="gate_id" required>${facilities.flatMap(() => []).join("")}${(await Promise.all(facilities.map((f) => api.gates(f.id)))).flat().map((g) => `<option value="${g.id}">${esc(g.name)}</option>`).join("")}</select></label><label>Scanner name<input name="name" required placeholder="Main gate QR reader" /></label><label>Device identifier<input name="device_identifier" required placeholder="SCN-CAMPUS-01" /></label><button class="primary-button" type="submit">Register scanner →</button><div id="scanner-message"></div></form></section></div><div class="two-column"><div>${sections.join("") || showEmpty("Create a parking place first")}</div><section class="panel"><div class="section-heading compact"><h2>Recent scan events</h2><span class="muted">Immutable operational log</span></div>${events.length ? `<div class="table-wrap"><table><thead><tr><th>Time</th><th>Type</th><th>Result</th><th>Reference</th></tr></thead><tbody>${events.slice(0, 20).map((e) => `<tr><td>${fmtDate(e.scanned_at)}</td><td>${esc(e.scan_type)}</td><td>${status(e.result)}</td><td>${esc(e.reference)}</td></tr>`).join("")}</tbody></table></div>` : showEmpty("No scans recorded")}</section></div>`;
  } catch (error) { return showError(errorText(error)); }
}

function scannerConsole() { return `<div class="page-title"><span class="eyebrow">DEVICE OPERATIONS</span><h1>Scanner console</h1><p>Use this screen on an attendant tablet or pair it with a camera/scanner app. Scanner keys are held only in this page session.</p></div><div class="form-panel"><form id="scanner-console-form"><label>Scanner ID<input name="scanner_id" type="number" min="1" required /></label><label>One-time scanner key<input name="api_key" type="password" autocomplete="off" required /></label><label>Scan type<select name="scan_type"><option value="ENTRY">Entry</option><option value="EXIT">Exit</option></select></label><label>Vehicle registration <span class="muted">for entry</span><input name="vehicle_registration" placeholder="ABC12345" /></label><label>Ticket QR token <span class="muted">for exit</span><textarea name="qr_token" placeholder="Paste the decoded signed ticket QR token"></textarea></label><button class="primary-button" type="submit">Submit scan →</button><div id="scanner-console-message"></div></form></div>`; }

async function renderPage() {
  if (!guard()) return;
  const active = route();
  if (!canAccess(active)) { app.innerHTML = layout(`<div class="state error-state"><b>Access denied</b><span>Your account does not have permission to view this page.</span></div>`, active); bind(); return; }
  app.innerHTML = layout(`<div class="loading"><span></span>Loading PARKWISE intelligence…</div>`, active);
  let content: string;
  if (active === "overview") content = role() === "ADMIN" ? await adminOverview() : await customerOverview();
  else if (active === "live-map") content = await liveMap();
  else if (active === "entry") content = await entryPage();
  else if (active === "exit") content = await exitPage();
  else if (active === "find-vehicle") content = await findVehicle();
  else if (active === "vehicles") content = await vehiclesPage();
  else if (active === "places") content = await places();
  else if (active === "layout") content = await layoutPage();
  else if (active === "reports") content = await reports();
  else if (active === "predictions") content = await predictions();
  else if (active === "feedback") content = feedback();
  else if (active === "operations") content = await operations();
  else if (active === "scanner-console") content = scannerConsole();
  else if (active === "admin") content = await admin();
  else content = `<div class="state"><b>Feature not configured</b><span>This route is reserved for an API integration not currently exposed by FastAPI.</span></div>`;
  app.innerHTML = layout(content, active); bind();
}

function bind() {
  document.querySelectorAll<HTMLElement>("[data-route]").forEach((item) => item.addEventListener("click", () => go(item.dataset.route || "overview")));
  document.querySelector<HTMLButtonElement>("#logout")?.addEventListener("click", async () => { await signOut(); go("login"); });
  document.querySelector<HTMLElement>("[data-refresh]")?.addEventListener("click", () => void renderPage());
  document.querySelector<HTMLFormElement>("#entry-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#form-message")!; try { const method = String(form.get("entry_method")); const result = await api.entry({ vehicle_id: Number(form.get("vehicle_id")), facility_id: Number(form.get("facility_id")), entry_method: method, slot_qr_token: String(form.get("slot_qr_token") || "") || null }); message.innerHTML = `<div class="success-state">Entry recorded. Assigned slot <b>${esc(result.slot_code)}</b> at ${esc(result.facility_name)}.</div>`; } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLFormElement>("#exit-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#form-message")!; try { const result = await api.exit({ ticket_id: String(form.get("ticket_id")), qr_token: String(form.get("qr_token")) }); message.innerHTML = `<div class="success-state">${esc(result.message)} Slot <b>${esc(result.slot_code)}</b> released after ${result.duration_minutes} minutes.</div>`; } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLFormElement>("#feedback-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const body: Record<string, unknown> = { category: form.get("category"), description: form.get("description"), reported_available_spaces: form.get("reported_available_spaces") ? Number(form.get("reported_available_spaces")) : null }; if (form.get("session_id")) body.session_id = Number(form.get("session_id")); const message = document.querySelector("#form-message")!; try { await api.feedback(body); message.innerHTML = `<div class="success-state">Feedback submitted successfully.</div>`; } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLFormElement>("#facility-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#facility-message")!; try { await api.createFacility({ name: String(form.get("name")), address: String(form.get("address")), total_capacity: Number(form.get("total_capacity")), price_per_hour: form.get("price_per_hour") ? Number(form.get("price_per_hour")) : 0, latitude: form.get("latitude") ? Number(form.get("latitude")) : null, longitude: form.get("longitude") ? Number(form.get("longitude")) : null }); message.innerHTML = `<div class="success-state">Parking place created. Configure its zones and slots next.</div>`; setTimeout(() => void renderPage(), 500); } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLFormElement>("#vehicle-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#vehicle-message")!; try { await api.addVehicle({ registration_number: String(form.get("registration_number")), vehicle_type: String(form.get("vehicle_type")) }); message.innerHTML = `<div class="success-state">Vehicle registered and ready for parking entry.</div>`; setTimeout(() => void renderPage(), 500); } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLFormElement>("#gate-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#gate-message")!; try { await api.createGate(Number(form.get("facility_id")), { name: String(form.get("name")), gate_type: String(form.get("gate_type")), is_active: true }); message.innerHTML = `<div class="success-state">Gate registered. Add its scanner next.</div>`; setTimeout(() => void renderPage(), 500); } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLFormElement>("#scanner-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#scanner-message")!; try { const scanner = await api.createScanner(Number(form.get("gate_id")), { name: String(form.get("name")), device_identifier: String(form.get("device_identifier")), is_active: true }); message.innerHTML = `<div class="success-state">Scanner registered. Save this one-time device key securely: <code>${esc(scanner.api_key)}</code></div>`; } catch (error) { message.innerHTML = showError(errorText(error)); } });
  document.querySelector<HTMLButtonElement>("#download-csv")?.addEventListener("click", async () => { try { const data = await api.exportCsv(90); const blob = new Blob([data], { type: "text/csv" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "parkwise-report.csv"; link.click(); URL.revokeObjectURL(link.href); } catch (error) { alert(errorText(error)); } });
  document.querySelector<HTMLButtonElement>("#download-xlsx")?.addEventListener("click", async () => { try { const blob = await api.exportXlsx(90); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "parkwise-report.xlsx"; link.click(); URL.revokeObjectURL(link.href); } catch (error) { alert(errorText(error)); } });
  document.querySelectorAll<HTMLButtonElement>("[data-revoke-scanner]").forEach((button) => button.addEventListener("click", async () => { if (!confirm("Revoke this scanner key? The device will stop working immediately.")) return; try { await api.revokeScanner(Number(button.dataset.revokeScanner)); await renderPage(); } catch (error) { alert(errorText(error)); } }));
  document.querySelectorAll<HTMLButtonElement>("[data-regenerate-scanner]").forEach((button) => button.addEventListener("click", async () => { try { const scanner = await api.regenerateScanner(Number(button.dataset.regenerateScanner)); alert(`Save this new one-time scanner key securely:\n\n${scanner.api_key}`); await renderPage(); } catch (error) { alert(errorText(error)); } }));
  document.querySelector<HTMLFormElement>("#scanner-console-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#scanner-console-message")!; const scanType = String(form.get("scan_type")); try { const result = await api.scannerScan(Number(form.get("scanner_id")), String(form.get("api_key")), { scan_type: scanType, vehicle_registration: String(form.get("vehicle_registration") || "") || undefined, qr_token: String(form.get("qr_token") || "") || undefined }); message.innerHTML = `<div class="success-state">${esc(scanType)} scan accepted. Parking state and scan history updated.</div><pre class="data-preview">${esc(JSON.stringify(result, null, 2))}</pre>`; } catch (error) { message.innerHTML = showError(errorText(error)); } });
}

function loginPage() { app.innerHTML = `<div class="login-shell"><div class="login-card"><div class="brand"><div class="brand-mark">◉</div><div><strong>PARKWISE</strong><small>PREDICTIVE PARKING INTELLIGENCE</small></div></div><span class="eyebrow">SECURE OPERATIONS PORTAL</span><h1>Welcome back.</h1><p>Sign in to manage vehicles, slots, tickets, and availability.</p><form id="login-form"><label>Email<input name="email" type="email" autocomplete="username" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" autocomplete="current-password" required /></label><button class="primary-button" type="submit">Sign in →</button><div id="login-message"></div></form><small class="muted">Access is enforced by the FastAPI backend. Passwords are never stored in the browser.</small></div></div>`; document.querySelector<HTMLFormElement>("#login-form")!.addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const message = document.querySelector("#login-message")!; message.innerHTML = `<div class="loading">Signing in…</div>`; try { await signIn(String(form.get("email")), String(form.get("password"))); go("overview"); } catch (error) { message.innerHTML = showError(errorText(error)); } }); }

window.addEventListener("popstate", () => { if (!isAuthenticated()) loginPage(); else void renderPage(); });
if (!isAuthenticated()) loginPage(); else void renderPage();
